# Generated by Django 2.0.2 on 2018-03-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estetdentsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
