# Generated by Django 2.0.2 on 2018-03-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estetdentsite', '0005_auto_20180321_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='photo',
            field=models.ImageField(blank=True, upload_to='spec_photo'),
        ),
    ]
