# Generated by Django 2.0.2 on 2018-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estetdentsite', '0008_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(),
        ),
    ]
